# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce9556c3242d85290e0aad68a9b23a90eab85720274a3cd01bff47e963c234f9e60db5871795079dea1bcca2089fa8d99f8c576fd017d97cbb100639ea52a861

test:
  secret_key_base: 091c99e94e1c8818492089b89d13a7529d9d2ffbfa5bff27461e3d385b66e7da1faa9e3477b7e053c8acd97391437c9ab24c27f9106e4d3dfc79e70ef5abbede

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
