# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc8e013e23c63496c8db05e94a2a0cc22be976510260d3de97bd4ea8592d6efa5e0b03a5f5a5779d29be08d0a88a25ab584cd4a6cbcb64ac819cb3565ee562ce

test:
  secret_key_base: ee817e3da2392292def42e91a36b875bec5a791e5834b309f9dd7c90668115f7bc90d7a2cdf4725a994dbd4e01a8355b54556b239e11156902412396ab5d784f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
